spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/liquibase-example
    username: fjrd

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml